#!/bin/bash

## Created By Aditya Shakya
## modified by Patrick Dano for a mate based system

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) mate-screensaver-command -l ;;
                *Logout) mate-session-save --logout-dialog ;;
                *Reboot) mate-session-save --shutdown-dialog ;;
                *Shutdown) systemctl -i poweroff
            esac
